spring:
  application:
    name: pangu-api
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: file:/opt/conf/pangu/application.properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  file:
    path: /opt/log/pangu-api
